create table FeedbackForm(
[Name] nvarchar(255) primary key ,
[Local Grade] nvarchar(255) ,
[Primary Skill] nvarchar(255) ,
[Project Code] float ,
[Project Name] nvarchar(255) ,
Practice nvarchar(255) ,
[Roll-Off End Date] date ,
[Reason for Roll Off] nvarchar(255) ,
[This release needs backfill/is backfilled] nvarchar(255) ,
[Performance Issue] nvarchar(255) ,
Resigned nvarchar(255) ,
[Under Probation] nvarchar(255) ,
[Long Leave] nvarchar(255) ,
[Technical Skill] nvarchar(255) ,
Communication nvarchar(255),
[Role/Competencies] nvarchar(255) ,
Remarks nvarchar(255) ,
[Relevant Experience(Years)] int,
[Leave Type] nvarchar(255) ,
[Other Reasons] nvarchar(255) ,
);